name: Run Channel 2 Agent

on:
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v6

      - name: Run Python agent
        run: python src/main.py